name: todo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  flutter_local_notifications: ^18.0.1
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.16
  hive_flutter: ^1.1.0
  go_router: ^14.6.1
  provider: ^6.1.2
  sizer: ^3.0.4
  intl: ^0.20.1
  uuid: ^4.5.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
